// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtRKYwMJXRyrcPxAY70ZRukt3JzQ9akc',
    appId: '1:763157132713:web:815abc816b6d23808ac0b8',
    messagingSenderId: '763157132713',
    projectId: 'parking-bt',
    authDomain: 'parking-bt.firebaseapp.com',
    databaseURL: 'https://parking-bt-default-rtdb.firebaseio.com',
    storageBucket: 'parking-bt.appspot.com',
    measurementId: 'G-XK994H0LWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_I56bPwGieALCWMMcr5_oEdNm-QnU754',
    appId: '1:763157132713:android:af9fee17444ccb9e8ac0b8',
    messagingSenderId: '763157132713',
    projectId: 'parking-bt',
    databaseURL: 'https://parking-bt-default-rtdb.firebaseio.com',
    storageBucket: 'parking-bt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6aru5EVND0X4_08rdDMzpaRj1fphGQk',
    appId: '1:763157132713:ios:4242bff7dccb873d8ac0b8',
    messagingSenderId: '763157132713',
    projectId: 'parking-bt',
    databaseURL: 'https://parking-bt-default-rtdb.firebaseio.com',
    storageBucket: 'parking-bt.appspot.com',
    iosBundleId: 'com.test.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD6aru5EVND0X4_08rdDMzpaRj1fphGQk',
    appId: '1:763157132713:ios:48c181da8368f1958ac0b8',
    messagingSenderId: '763157132713',
    projectId: 'parking-bt',
    databaseURL: 'https://parking-bt-default-rtdb.firebaseio.com',
    storageBucket: 'parking-bt.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
